export const LOGIN_SUCCESS = "LOGIN";
export const LOGOUT = "LOGOUT";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const SIGNUP = "SIGNUP";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

export enum authStateActions {
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGOUT = "LOGOUT",
  LOGIN_FAILED = "LOGIN_FAILED",
  SIGNUP = "SIGNUP",
  SIGNUP_FAILED = "SIGNUP_FAILED",
  SIGNUP_SUCCESS = "SIGNUP_SUCCESS",
}
