export const SET_CURRENT_ATTEMPT = "SET_CURRENT_ATTEMPT";
export const SET_PREVIOUS_ATTEMPT = "SET_PREVIOUS_ATTEMPT";
export const SET_GAME_OVER_MESSAGE = "SET_GAME_OVER_MESSAGE";
export const APPEND_CURRENT_ATTEMPT = "APPEND_CURRENT_ATTEMPT";
export const APPEND_PREVIOUS_ATTEMPT = "APPEND_PREVIOUS_ATTEMPT";
export const BACKSPACE_CURRENT_ATTEMPT = "BACKSPACE_CURRENT_ATTEMPT";
export const RESET_GAME_STATE = "RESET_GAME_STATE";
